// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: ctl_device.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Projects      []string               `protobuf:"bytes,4,rep,name=projects,proto3" json:"projects,omitempty"`
	Resume        bool                   `protobuf:"varint,5,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_ctl_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetProjects() []string {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *RegisterRequest) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PendingTasks  []*Task                `protobuf:"bytes,2,rep,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_ctl_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetPendingTasks() []*Task {
	if x != nil {
		return x.PendingTasks
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_ctl_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_ctl_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_ctl_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{4}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_ctl_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{5}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Online        bool                   `protobuf:"varint,5,opt,name=online,proto3" json:"online,omitempty"`
	CurrentTask   string                 `protobuf:"bytes,6,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_ctl_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{6}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Agent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Agent) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

func (x *Agent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Agent) GetCurrentTask() string {
	if x != nil {
		return x.CurrentTask
	}
	return ""
}

type ProjectRegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dir            string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Tech           string                 `protobuf:"bytes,3,opt,name=tech,proto3" json:"tech,omitempty"`
	TestCmd        string                 `protobuf:"bytes,4,opt,name=test_cmd,json=testCmd,proto3" json:"test_cmd,omitempty"`
	Executor       string                 `protobuf:"bytes,5,opt,name=executor,proto3" json:"executor,omitempty"`
	TimeoutMinutes int32                  `protobuf:"varint,6,opt,name=timeout_minutes,json=timeoutMinutes,proto3" json:"timeout_minutes,omitempty"`
	NotifyChannel  string                 `protobuf:"bytes,7,opt,name=notify_channel,json=notifyChannel,proto3" json:"notify_channel,omitempty"`
	NotifyTarget   string                 `protobuf:"bytes,8,opt,name=notify_target,json=notifyTarget,proto3" json:"notify_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectRegisterRequest) Reset() {
	*x = ProjectRegisterRequest{}
	mi := &file_ctl_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegisterRequest) ProtoMessage() {}

func (x *ProjectRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegisterRequest.ProtoReflect.Descriptor instead.
func (*ProjectRegisterRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectRegisterRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *ProjectRegisterRequest) GetTech() string {
	if x != nil {
		return x.Tech
	}
	return ""
}

func (x *ProjectRegisterRequest) GetTestCmd() string {
	if x != nil {
		return x.TestCmd
	}
	return ""
}

func (x *ProjectRegisterRequest) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *ProjectRegisterRequest) GetTimeoutMinutes() int32 {
	if x != nil {
		return x.TimeoutMinutes
	}
	return 0
}

func (x *ProjectRegisterRequest) GetNotifyChannel() string {
	if x != nil {
		return x.NotifyChannel
	}
	return ""
}

func (x *ProjectRegisterRequest) GetNotifyTarget() string {
	if x != nil {
		return x.NotifyTarget
	}
	return ""
}

type ProjectRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRegisterResponse) Reset() {
	*x = ProjectRegisterResponse{}
	mi := &file_ctl_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegisterResponse) ProtoMessage() {}

func (x *ProjectRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegisterResponse.ProtoReflect.Descriptor instead.
func (*ProjectRegisterResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectRegisterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProjectListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectListRequest) Reset() {
	*x = ProjectListRequest{}
	mi := &file_ctl_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectListRequest) ProtoMessage() {}

func (x *ProjectListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectListRequest.ProtoReflect.Descriptor instead.
func (*ProjectListRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{9}
}

type ProjectListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Tasks         map[string]*TaskList   `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectListResponse) Reset() {
	*x = ProjectListResponse{}
	mi := &file_ctl_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectListResponse) ProtoMessage() {}

func (x *ProjectListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectListResponse.ProtoReflect.Descriptor instead.
func (*ProjectListResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectListResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ProjectListResponse) GetTasks() map[string]*TaskList {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Project struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dir            string                 `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	Tech           string                 `protobuf:"bytes,3,opt,name=tech,proto3" json:"tech,omitempty"`
	TestCmd        string                 `protobuf:"bytes,4,opt,name=test_cmd,json=testCmd,proto3" json:"test_cmd,omitempty"`
	Executor       string                 `protobuf:"bytes,5,opt,name=executor,proto3" json:"executor,omitempty"`
	TimeoutMinutes int32                  `protobuf:"varint,6,opt,name=timeout_minutes,json=timeoutMinutes,proto3" json:"timeout_minutes,omitempty"`
	NotifyChannel  string                 `protobuf:"bytes,7,opt,name=notify_channel,json=notifyChannel,proto3" json:"notify_channel,omitempty"`
	NotifyTarget   string                 `protobuf:"bytes,8,opt,name=notify_target,json=notifyTarget,proto3" json:"notify_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_ctl_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{11}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Project) GetTech() string {
	if x != nil {
		return x.Tech
	}
	return ""
}

func (x *Project) GetTestCmd() string {
	if x != nil {
		return x.TestCmd
	}
	return ""
}

func (x *Project) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *Project) GetTimeoutMinutes() int32 {
	if x != nil {
		return x.TimeoutMinutes
	}
	return 0
}

func (x *Project) GetNotifyChannel() string {
	if x != nil {
		return x.NotifyChannel
	}
	return ""
}

func (x *Project) GetNotifyTarget() string {
	if x != nil {
		return x.NotifyTarget
	}
	return ""
}

type TaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskList) Reset() {
	*x = TaskList{}
	mi := &file_ctl_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskList) ProtoMessage() {}

func (x *TaskList) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskList.ProtoReflect.Descriptor instead.
func (*TaskList) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{12}
}

func (x *TaskList) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type Task struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Project            string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Num                string                 `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Name               string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	AcceptanceCriteria []string               `protobuf:"bytes,6,rep,name=acceptance_criteria,json=acceptanceCriteria,proto3" json:"acceptance_criteria,omitempty"`
	ContextFiles       []string               `protobuf:"bytes,7,rep,name=context_files,json=contextFiles,proto3" json:"context_files,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	AssignedTo         string                 `protobuf:"bytes,9,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	StartedAt          string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Commit             string                 `protobuf:"bytes,12,opt,name=commit,proto3" json:"commit,omitempty"`
	Report             string                 `protobuf:"bytes,13,opt,name=report,proto3" json:"report,omitempty"`
	TimeoutMinutes     int32                  `protobuf:"varint,14,opt,name=timeout_minutes,json=timeoutMinutes,proto3" json:"timeout_minutes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_ctl_device_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{13}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Task) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetAcceptanceCriteria() []string {
	if x != nil {
		return x.AcceptanceCriteria
	}
	return nil
}

func (x *Task) GetContextFiles() []string {
	if x != nil {
		return x.ContextFiles
	}
	return nil
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Task) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Task) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Task) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *Task) GetReport() string {
	if x != nil {
		return x.Report
	}
	return ""
}

func (x *Task) GetTimeoutMinutes() int32 {
	if x != nil {
		return x.TimeoutMinutes
	}
	return 0
}

type TaskGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskGetRequest) Reset() {
	*x = TaskGetRequest{}
	mi := &file_ctl_device_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskGetRequest) ProtoMessage() {}

func (x *TaskGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskGetRequest.ProtoReflect.Descriptor instead.
func (*TaskGetRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{14}
}

func (x *TaskGetRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type TaskGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskGetResponse) Reset() {
	*x = TaskGetResponse{}
	mi := &file_ctl_device_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskGetResponse) ProtoMessage() {}

func (x *TaskGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskGetResponse.ProtoReflect.Descriptor instead.
func (*TaskGetResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{15}
}

func (x *TaskGetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskGetResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	TaskNum       string                 `protobuf:"bytes,2,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_ctl_device_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{16}
}

func (x *TaskStatusRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TaskStatusRequest) GetTaskNum() string {
	if x != nil {
		return x.TaskNum
	}
	return ""
}

func (x *TaskStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_ctl_device_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{17}
}

func (x *TaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	TaskNum       string                 `protobuf:"bytes,2,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Commit        string                 `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	TestOutput    string                 `protobuf:"bytes,5,opt,name=test_output,json=testOutput,proto3" json:"test_output,omitempty"`
	Issues        string                 `protobuf:"bytes,6,opt,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompleteRequest) Reset() {
	*x = TaskCompleteRequest{}
	mi := &file_ctl_device_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleteRequest) ProtoMessage() {}

func (x *TaskCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleteRequest.ProtoReflect.Descriptor instead.
func (*TaskCompleteRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{18}
}

func (x *TaskCompleteRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TaskCompleteRequest) GetTaskNum() string {
	if x != nil {
		return x.TaskNum
	}
	return ""
}

func (x *TaskCompleteRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TaskCompleteRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *TaskCompleteRequest) GetTestOutput() string {
	if x != nil {
		return x.TestOutput
	}
	return ""
}

func (x *TaskCompleteRequest) GetIssues() string {
	if x != nil {
		return x.Issues
	}
	return ""
}

type TaskCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompleteResponse) Reset() {
	*x = TaskCompleteResponse{}
	mi := &file_ctl_device_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleteResponse) ProtoMessage() {}

func (x *TaskCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleteResponse.ProtoReflect.Descriptor instead.
func (*TaskCompleteResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{19}
}

func (x *TaskCompleteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	TaskNum       string                 `protobuf:"bytes,2,opt,name=task_num,json=taskNum,proto3" json:"task_num,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskBlockRequest) Reset() {
	*x = TaskBlockRequest{}
	mi := &file_ctl_device_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskBlockRequest) ProtoMessage() {}

func (x *TaskBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskBlockRequest.ProtoReflect.Descriptor instead.
func (*TaskBlockRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{20}
}

func (x *TaskBlockRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TaskBlockRequest) GetTaskNum() string {
	if x != nil {
		return x.TaskNum
	}
	return ""
}

func (x *TaskBlockRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TaskBlockRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type TaskBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskBlockResponse) Reset() {
	*x = TaskBlockResponse{}
	mi := &file_ctl_device_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskBlockResponse) ProtoMessage() {}

func (x *TaskBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskBlockResponse.ProtoReflect.Descriptor instead.
func (*TaskBlockResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{21}
}

func (x *TaskBlockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskDispatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDispatchRequest) Reset() {
	*x = TaskDispatchRequest{}
	mi := &file_ctl_device_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDispatchRequest) ProtoMessage() {}

func (x *TaskDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDispatchRequest.ProtoReflect.Descriptor instead.
func (*TaskDispatchRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{22}
}

func (x *TaskDispatchRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TaskDispatchRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDispatchResponse) Reset() {
	*x = TaskDispatchResponse{}
	mi := &file_ctl_device_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDispatchResponse) ProtoMessage() {}

func (x *TaskDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDispatchResponse.ProtoReflect.Descriptor instead.
func (*TaskDispatchResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{23}
}

func (x *TaskDispatchResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TaskAdvanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAdvanceRequest) Reset() {
	*x = TaskAdvanceRequest{}
	mi := &file_ctl_device_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAdvanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAdvanceRequest) ProtoMessage() {}

func (x *TaskAdvanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAdvanceRequest.ProtoReflect.Descriptor instead.
func (*TaskAdvanceRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{24}
}

func (x *TaskAdvanceRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type TaskAdvanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAdvanceResponse) Reset() {
	*x = TaskAdvanceResponse{}
	mi := &file_ctl_device_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAdvanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAdvanceResponse) ProtoMessage() {}

func (x *TaskAdvanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAdvanceResponse.ProtoReflect.Descriptor instead.
func (*TaskAdvanceResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{25}
}

func (x *TaskAdvanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ctl_device_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{26}
}

func (x *SubscribeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_ctl_device_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ctl_device_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_ctl_device_proto_rawDescGZIP(), []int{27}
}

func (x *EventResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventResponse) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *EventResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EventResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EventResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *EventResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_ctl_device_proto protoreflect.FileDescriptor

const file_ctl_device_proto_rawDesc = "" +
	"\n" +
	"\x10ctl_device.proto\x12\tctldevice\"\x98\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1a\n" +
	"\bprojects\x18\x04 \x03(\tR\bprojects\x12\x16\n" +
	"\x06resume\x18\x05 \x01(\bR\x06resume\"X\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x124\n" +
	"\rpending_tasks\x18\x02 \x03(\v2\x0f.ctldevice.TaskR\fpendingTasks\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x13\n" +
	"\x11ListAgentsRequest\">\n" +
	"\x12ListAgentsResponse\x12(\n" +
	"\x06agents\x18\x01 \x03(\v2\x10.ctldevice.AgentR\x06agents\"\xb1\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\tR\rlastHeartbeat\x12\x16\n" +
	"\x06online\x18\x05 \x01(\bR\x06online\x12!\n" +
	"\fcurrent_task\x18\x06 \x01(\tR\vcurrentTask\"\xfe\x01\n" +
	"\x16ProjectRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\x12\x12\n" +
	"\x04tech\x18\x03 \x01(\tR\x04tech\x12\x19\n" +
	"\btest_cmd\x18\x04 \x01(\tR\atestCmd\x12\x1a\n" +
	"\bexecutor\x18\x05 \x01(\tR\bexecutor\x12'\n" +
	"\x0ftimeout_minutes\x18\x06 \x01(\x05R\x0etimeoutMinutes\x12%\n" +
	"\x0enotify_channel\x18\a \x01(\tR\rnotifyChannel\x12#\n" +
	"\rnotify_target\x18\b \x01(\tR\fnotifyTarget\"1\n" +
	"\x17ProjectRegisterResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x14\n" +
	"\x12ProjectListRequest\"\xd5\x01\n" +
	"\x13ProjectListResponse\x12.\n" +
	"\bprojects\x18\x01 \x03(\v2\x12.ctldevice.ProjectR\bprojects\x12?\n" +
	"\x05tasks\x18\x02 \x03(\v2).ctldevice.ProjectListResponse.TasksEntryR\x05tasks\x1aM\n" +
	"\n" +
	"TasksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.ctldevice.TaskListR\x05value:\x028\x01\"\xef\x01\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dir\x18\x02 \x01(\tR\x03dir\x12\x12\n" +
	"\x04tech\x18\x03 \x01(\tR\x04tech\x12\x19\n" +
	"\btest_cmd\x18\x04 \x01(\tR\atestCmd\x12\x1a\n" +
	"\bexecutor\x18\x05 \x01(\tR\bexecutor\x12'\n" +
	"\x0ftimeout_minutes\x18\x06 \x01(\x05R\x0etimeoutMinutes\x12%\n" +
	"\x0enotify_channel\x18\a \x01(\tR\rnotifyChannel\x12#\n" +
	"\rnotify_target\x18\b \x01(\tR\fnotifyTarget\"1\n" +
	"\bTaskList\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.ctldevice.TaskR\x05tasks\"\x9e\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x10\n" +
	"\x03num\x18\x03 \x01(\tR\x03num\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12/\n" +
	"\x13acceptance_criteria\x18\x06 \x03(\tR\x12acceptanceCriteria\x12#\n" +
	"\rcontext_files\x18\a \x03(\tR\fcontextFiles\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\t \x01(\tR\n" +
	"assignedTo\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x16\n" +
	"\x06commit\x18\f \x01(\tR\x06commit\x12\x16\n" +
	"\x06report\x18\r \x01(\tR\x06report\x12'\n" +
	"\x0ftimeout_minutes\x18\x0e \x01(\x05R\x0etimeoutMinutes\"*\n" +
	"\x0eTaskGetRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"N\n" +
	"\x0fTaskGetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\x04task\x18\x02 \x01(\v2\x0f.ctldevice.TaskR\x04task\"`\n" +
	"\x11TaskStatusRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x19\n" +
	"\btask_num\x18\x02 \x01(\tR\ataskNum\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\",\n" +
	"\x12TaskStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb5\x01\n" +
	"\x13TaskCompleteRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x19\n" +
	"\btask_num\x18\x02 \x01(\tR\ataskNum\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x16\n" +
	"\x06commit\x18\x04 \x01(\tR\x06commit\x12\x1f\n" +
	"\vtest_output\x18\x05 \x01(\tR\n" +
	"testOutput\x12\x16\n" +
	"\x06issues\x18\x06 \x01(\tR\x06issues\".\n" +
	"\x14TaskCompleteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"y\n" +
	"\x10TaskBlockRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x19\n" +
	"\btask_num\x18\x02 \x01(\tR\ataskNum\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\"+\n" +
	"\x11TaskBlockResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"T\n" +
	"\x13TaskDispatchRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12#\n" +
	"\x04task\x18\x02 \x01(\v2\x0f.ctldevice.TaskR\x04task\".\n" +
	"\x14TaskDispatchResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\".\n" +
	"\x12TaskAdvanceRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"-\n" +
	"\x13TaskAdvanceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\",\n" +
	"\x10SubscribeRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\xa9\x01\n" +
	"\rEventResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp2\xe6\x01\n" +
	"\fAgentService\x12C\n" +
	"\bRegister\x12\x1a.ctldevice.RegisterRequest\x1a\x1b.ctldevice.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.ctldevice.HeartbeatRequest\x1a\x1c.ctldevice.HeartbeatResponse\x12I\n" +
	"\n" +
	"ListAgents\x12\x1c.ctldevice.ListAgentsRequest\x1a\x1d.ctldevice.ListAgentsResponse2\xaa\x01\n" +
	"\x0eProjectService\x12Q\n" +
	"\bRegister\x12!.ctldevice.ProjectRegisterRequest\x1a\".ctldevice.ProjectRegisterResponse\x12E\n" +
	"\x04List\x12\x1d.ctldevice.ProjectListRequest\x1a\x1e.ctldevice.ProjectListResponse2\xc0\x03\n" +
	"\vTaskService\x12<\n" +
	"\x03Get\x12\x19.ctldevice.TaskGetRequest\x1a\x1a.ctldevice.TaskGetResponse\x12K\n" +
	"\fUpdateStatus\x12\x1c.ctldevice.TaskStatusRequest\x1a\x1d.ctldevice.TaskStatusResponse\x12K\n" +
	"\bComplete\x12\x1e.ctldevice.TaskCompleteRequest\x1a\x1f.ctldevice.TaskCompleteResponse\x12B\n" +
	"\x05Block\x12\x1b.ctldevice.TaskBlockRequest\x1a\x1c.ctldevice.TaskBlockResponse\x12K\n" +
	"\bDispatch\x12\x1e.ctldevice.TaskDispatchRequest\x1a\x1f.ctldevice.TaskDispatchResponse\x12H\n" +
	"\aAdvance\x12\x1d.ctldevice.TaskAdvanceRequest\x1a\x1e.ctldevice.TaskAdvanceResponse2T\n" +
	"\fEventService\x12D\n" +
	"\tSubscribe\x12\x1b.ctldevice.SubscribeRequest\x1a\x18.ctldevice.EventResponse0\x01B(Z&github.com/0xdevelop/ctl_device/api/pbb\x06proto3"

var (
	file_ctl_device_proto_rawDescOnce sync.Once
	file_ctl_device_proto_rawDescData []byte
)

func file_ctl_device_proto_rawDescGZIP() []byte {
	file_ctl_device_proto_rawDescOnce.Do(func() {
		file_ctl_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ctl_device_proto_rawDesc), len(file_ctl_device_proto_rawDesc)))
	})
	return file_ctl_device_proto_rawDescData
}

var file_ctl_device_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ctl_device_proto_goTypes = []any{
	(*RegisterRequest)(nil),         // 0: ctldevice.RegisterRequest
	(*RegisterResponse)(nil),        // 1: ctldevice.RegisterResponse
	(*HeartbeatRequest)(nil),        // 2: ctldevice.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: ctldevice.HeartbeatResponse
	(*ListAgentsRequest)(nil),       // 4: ctldevice.ListAgentsRequest
	(*ListAgentsResponse)(nil),      // 5: ctldevice.ListAgentsResponse
	(*Agent)(nil),                   // 6: ctldevice.Agent
	(*ProjectRegisterRequest)(nil),  // 7: ctldevice.ProjectRegisterRequest
	(*ProjectRegisterResponse)(nil), // 8: ctldevice.ProjectRegisterResponse
	(*ProjectListRequest)(nil),      // 9: ctldevice.ProjectListRequest
	(*ProjectListResponse)(nil),     // 10: ctldevice.ProjectListResponse
	(*Project)(nil),                 // 11: ctldevice.Project
	(*TaskList)(nil),                // 12: ctldevice.TaskList
	(*Task)(nil),                    // 13: ctldevice.Task
	(*TaskGetRequest)(nil),          // 14: ctldevice.TaskGetRequest
	(*TaskGetResponse)(nil),         // 15: ctldevice.TaskGetResponse
	(*TaskStatusRequest)(nil),       // 16: ctldevice.TaskStatusRequest
	(*TaskStatusResponse)(nil),      // 17: ctldevice.TaskStatusResponse
	(*TaskCompleteRequest)(nil),     // 18: ctldevice.TaskCompleteRequest
	(*TaskCompleteResponse)(nil),    // 19: ctldevice.TaskCompleteResponse
	(*TaskBlockRequest)(nil),        // 20: ctldevice.TaskBlockRequest
	(*TaskBlockResponse)(nil),       // 21: ctldevice.TaskBlockResponse
	(*TaskDispatchRequest)(nil),     // 22: ctldevice.TaskDispatchRequest
	(*TaskDispatchResponse)(nil),    // 23: ctldevice.TaskDispatchResponse
	(*TaskAdvanceRequest)(nil),      // 24: ctldevice.TaskAdvanceRequest
	(*TaskAdvanceResponse)(nil),     // 25: ctldevice.TaskAdvanceResponse
	(*SubscribeRequest)(nil),        // 26: ctldevice.SubscribeRequest
	(*EventResponse)(nil),           // 27: ctldevice.EventResponse
	nil,                             // 28: ctldevice.ProjectListResponse.TasksEntry
}
var file_ctl_device_proto_depIdxs = []int32{
	13, // 0: ctldevice.RegisterResponse.pending_tasks:type_name -> ctldevice.Task
	6,  // 1: ctldevice.ListAgentsResponse.agents:type_name -> ctldevice.Agent
	11, // 2: ctldevice.ProjectListResponse.projects:type_name -> ctldevice.Project
	28, // 3: ctldevice.ProjectListResponse.tasks:type_name -> ctldevice.ProjectListResponse.TasksEntry
	13, // 4: ctldevice.TaskList.tasks:type_name -> ctldevice.Task
	13, // 5: ctldevice.TaskGetResponse.task:type_name -> ctldevice.Task
	13, // 6: ctldevice.TaskDispatchRequest.task:type_name -> ctldevice.Task
	12, // 7: ctldevice.ProjectListResponse.TasksEntry.value:type_name -> ctldevice.TaskList
	0,  // 8: ctldevice.AgentService.Register:input_type -> ctldevice.RegisterRequest
	2,  // 9: ctldevice.AgentService.Heartbeat:input_type -> ctldevice.HeartbeatRequest
	4,  // 10: ctldevice.AgentService.ListAgents:input_type -> ctldevice.ListAgentsRequest
	7,  // 11: ctldevice.ProjectService.Register:input_type -> ctldevice.ProjectRegisterRequest
	9,  // 12: ctldevice.ProjectService.List:input_type -> ctldevice.ProjectListRequest
	14, // 13: ctldevice.TaskService.Get:input_type -> ctldevice.TaskGetRequest
	16, // 14: ctldevice.TaskService.UpdateStatus:input_type -> ctldevice.TaskStatusRequest
	18, // 15: ctldevice.TaskService.Complete:input_type -> ctldevice.TaskCompleteRequest
	20, // 16: ctldevice.TaskService.Block:input_type -> ctldevice.TaskBlockRequest
	22, // 17: ctldevice.TaskService.Dispatch:input_type -> ctldevice.TaskDispatchRequest
	24, // 18: ctldevice.TaskService.Advance:input_type -> ctldevice.TaskAdvanceRequest
	26, // 19: ctldevice.EventService.Subscribe:input_type -> ctldevice.SubscribeRequest
	1,  // 20: ctldevice.AgentService.Register:output_type -> ctldevice.RegisterResponse
	3,  // 21: ctldevice.AgentService.Heartbeat:output_type -> ctldevice.HeartbeatResponse
	5,  // 22: ctldevice.AgentService.ListAgents:output_type -> ctldevice.ListAgentsResponse
	8,  // 23: ctldevice.ProjectService.Register:output_type -> ctldevice.ProjectRegisterResponse
	10, // 24: ctldevice.ProjectService.List:output_type -> ctldevice.ProjectListResponse
	15, // 25: ctldevice.TaskService.Get:output_type -> ctldevice.TaskGetResponse
	17, // 26: ctldevice.TaskService.UpdateStatus:output_type -> ctldevice.TaskStatusResponse
	19, // 27: ctldevice.TaskService.Complete:output_type -> ctldevice.TaskCompleteResponse
	21, // 28: ctldevice.TaskService.Block:output_type -> ctldevice.TaskBlockResponse
	23, // 29: ctldevice.TaskService.Dispatch:output_type -> ctldevice.TaskDispatchResponse
	25, // 30: ctldevice.TaskService.Advance:output_type -> ctldevice.TaskAdvanceResponse
	27, // 31: ctldevice.EventService.Subscribe:output_type -> ctldevice.EventResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ctl_device_proto_init() }
func file_ctl_device_proto_init() {
	if File_ctl_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ctl_device_proto_rawDesc), len(file_ctl_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_ctl_device_proto_goTypes,
		DependencyIndexes: file_ctl_device_proto_depIdxs,
		MessageInfos:      file_ctl_device_proto_msgTypes,
	}.Build()
	File_ctl_device_proto = out.File
	file_ctl_device_proto_goTypes = nil
	file_ctl_device_proto_depIdxs = nil
}
